import ast
def outer():
 def inner_0(text):
  return ast.parse(text)
 def inner_1(text):
  return ast.parse(text)
 def inner_2(text):
  return ast.parse(text)
 def inner_3(text):
  return ast.parse(text)
 def inner_4(text):
  return ast.parse(text)
 def inner_5(text):
  return ast.parse(text)
 def inner_6(text):
  return ast.parse(text)
 def inner_7(text):
  return ast.parse(text)
 def inner_8(text):
  return ast.parse(text)
 def inner_9(text):
  return ast.parse(text)
 def inner_10(text):
  return ast.parse(text)
 def inner_11(text):
  return ast.parse(text)
 def inner_12(text):
  return ast.parse(text)
 def inner_13(text):
  return ast.parse(text)
 def inner_14(text):
  return ast.parse(text)
 def inner_15(text):
  return ast.parse(text)
 def inner_16(text):
  return ast.parse(text)
 def inner_17(text):
  return ast.parse(text)
 def inner_18(text):
  return ast.parse(text)
 def inner_19(text):
  return ast.parse(text)
 def inner_20(text):
  return ast.parse(text)
 def inner_21(text):
  return ast.parse(text)
 def inner_22(text):
  return ast.parse(text)
 def inner_23(text):
  return ast.parse(text)
 def inner_24(text):
  return ast.parse(text)
 def inner_25(text):
  return ast.parse(text)
 def inner_26(text):
  return ast.parse(text)
 def inner_27(text):
  return ast.parse(text)
 def inner_28(text):
  return ast.parse(text)
 def inner_29(text):
  return ast.parse(text)
 def inner_30(text):
  return ast.parse(text)
 def inner_31(text):
  return ast.parse(text)
 def inner_32(text):
  return ast.parse(text)
 def inner_33(text):
  return ast.parse(text)
 def inner_34(text):
  return ast.parse(text)
 def inner_35(text):
  return ast.parse(text)
 def inner_36(text):
  return ast.parse(text)
 def inner_37(text):
  return ast.parse(text)
 def inner_38(text):
  return ast.parse(text)
 def inner_39(text):
  return ast.parse(text)
 def inner_40(text):
  return ast.parse(text)
 def inner_41(text):
  return ast.parse(text)
 def inner_42(text):
  return ast.parse(text)
 def inner_43(text):
  return ast.parse(text)
 def inner_44(text):
  return ast.parse(text)
 def inner_45(text):
  return ast.parse(text)
 def inner_46(text):
  return ast.parse(text)
 def inner_47(text):
  return ast.parse(text)
 def inner_48(text):
  return ast.parse(text)
 def inner_49(text):
  return ast.parse(text)
 def inner_50(text):
  return ast.parse(text)
 def inner_51(text):
  return ast.parse(text)
 def inner_52(text):
  return ast.parse(text)
 def inner_53(text):
  return ast.parse(text)
 def inner_54(text):
  return ast.parse(text)
 def inner_55(text):
  return ast.parse(text)
 def inner_56(text):
  return ast.parse(text)
 def inner_57(text):
  return ast.parse(text)
 def inner_58(text):
  return ast.parse(text)
 def inner_59(text):
  return ast.parse(text)
 def inner_60(text):
  return ast.parse(text)
 def inner_61(text):
  return ast.parse(text)
 def inner_62(text):
  return ast.parse(text)
 def inner_63(text):
  return ast.parse(text)
 def inner_64(text):
  return ast.parse(text)
 def inner_65(text):
  return ast.parse(text)
 def inner_66(text):
  return ast.parse(text)
 def inner_67(text):
  return ast.parse(text)
 def inner_68(text):
  return ast.parse(text)
 def inner_69(text):
  return ast.parse(text)
 def inner_70(text):
  return ast.parse(text)
 def inner_71(text):
  return ast.parse(text)
 def inner_72(text):
  return ast.parse(text)
 def inner_73(text):
  return ast.parse(text)
 def inner_74(text):
  return ast.parse(text)
 def inner_75(text):
  return ast.parse(text)
 def inner_76(text):
  return ast.parse(text)
 def inner_77(text):
  return ast.parse(text)
 def inner_78(text):
  return ast.parse(text)
 def inner_79(text):
  return ast.parse(text)
 return inner_0
